In [5]:
from numpy import random as rnd
import numpy as np

In [6]:
rng = rnd.default_rng()


In [23]:
a = np.load("./aa.npy")

In [29]:
a.shape

(10, 20, 20)

In [7]:
b=rng.integers(0,2,size=(3,10))

In [11]:
b

array([[1, 1, 1, 1, 1, 1, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 1, 1, 0, 1, 1],
       [0, 0, 0, 1, 1, 0, 1, 1, 0, 0]])

In [62]:
a = np.zeros(5)

In [53]:
a[[0,4]] = 1

In [67]:
a =a.astype(int)

In [68]:
a

array([0, 0, 0, 0, 0])

In [59]:
length = 10
z=[]
for i in range(1):
    l = length*length
    lattice = np.ones(l)

    # create indices to be modified to 0
    indices = rng.integers(0,l, size=int(0.05*l))
    lattice[indices] = 0

    z.append(lattice)

# create square lattice of 01 of size=length


np.save(f"./dummy_data/{length}_lowT", z)

In [69]:
lattice

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])